VDB-4527 gmake-cmake bridge

diff --git a/build/Makefile.env b/build/Makefile.env
--- a/build/Makefile.env
+++ b/build/Makefile.env
@@ -22,403 +22,131 @@
 #
 # ===========================================================================
 
-# pick up dependencies from object directory
-ifdef SRCDIR
-	include $(wildcard *.d)
-endif
+default all std: makedirs cmake
 
 # determine shell environment
-include $(TOP)/build/Makefile.shell
+CONFIG_FILE = $(TOP)/build/Makefile.config
+ifeq (no, $(shell test -f $(CONFIG_FILE) && echo yes || echo no))
+    $(error "*** File '$(CONFIG_FILE)' is missing. Please run $(TOP)/build/configure")
+endif
+
+# determine SRCDIR
+ifdef MODULE
+    SRCDIR=$(TOP)/$(MODULE)
+else
+    SRCDIR=$(TOP)/
+endif
 
 # load build configuration
+CURDIR = $(SRCDIR)
 include $(CONFIG_FILE)
 
-# normally build shared and static external libs
-LIBEXT = $(LIBX) $(SHLX)
-
-# normally build static intermediate libs
-ILIBEXT = $(LIBX)
-
-# determine BUILD
-ifeq (,$(BUILD))
-	BUILD = dbg
-endif
-
-# some rules are sensitive to the type of build
-BUILDTYPE = $(BUILD)
-
-# adjust settings for build
-ifeq (dbg,$(BUILD))
-	DEBUG := -D_DEBUGGING
-endif
-ifeq (prof,$(BUILD))
-	DEBUG := -D_PROFILING
-endif
-ifeq (pur,$(BUILD))
-	DEBUG := -D_DEBUGGING
-	LD_PRE := purify
-	LNKG = stat
-endif
-ifeq (pcov,$(BUILD))
-	DEBUG := -D_DEBUGGING
-	LD_PRE := purecov
-	LNKG = stat
-endif
-ifeq (scm,$(BUILD))
-	BUILDTYPE = rel
-	CHECKSUM := --checksum
-endif
-
-ifeq (yes,$(HAS_RHOST))
-	LOCAL_OR_REMOTE = remote
-else
-	LOCAL_OR_REMOTE = local
-endif
-
-# pre-built sra-tools are static
-ifeq (1,$(WANTS_STATIC))
-	STATIC = --static
-	STATICSYSLIBS = --static-system-libs
-endif
-
-# drop all suffix rules
-.SUFFIXES:
-
-# load OS and COMP specific files
-include $(TOP)/build/Makefile.$(OS)
-include $(TOP)/build/Makefile.$(COMP)
-include $(TOP)/build/Makefile.rules
-
-# external schema modules
-EXT_SCHEMA_MODULES = axf sraxf wgsxf vxf
-UPDATE_SCHEMA_LIBS := $(addprefix -lw,$(EXT_SCHEMA_MODULES))
-READONLY_SCHEMA_LIBS = $(addprefix -l,$(EXT_SCHEMA_MODULES))
-ALWAYS_STATIC_SCHEMA_LIBS = $(addprefix -s,$(EXT_SCHEMA_MODULES))
-
-# full directory paths
-TARGDIR ?= $(OUTDIR)/$(OS)/$(TOOLSET)/$(ARCH)/$(BUILD)
-BINDIR ?= $(TARGDIR)/bin
-ifeq (win,$(OS))
-    # on Windows, place test executables next to .dlls
-    TEST_BINDIR = $(BINDIR)
-else
-    TEST_BINDIR = $(TARGDIR)/test-bin
-endif
-ILIBDIR = $(TARGDIR)/ilib
-LIBDIR = $(TARGDIR)/lib
-OBJDIR = $(TARGDIR)/obj/$(MODULE)
-
-CLSPATH         ?= $(TARGDIR)/java
-CLASSPATH       ?= $(CLSPATH)
-CLASSDIR        ?= $(TARGDIR)/$(MODULE)
-TEST_CLSPATH    ?= $(OUTDIR)/test/java
-JAVASOURCEPATH  ?= $(TOP)/java
-
-# path to the ncbi sub-directory
-# this is where modules and installed schema files are kept
-ifeq (win,$(OS))
-    # under Windows, we are always relative to binary path
-	NCBIDIR = $(BINDIR)/ncbi
-else
-	# under Linux and Mac, it can be binary or library
-	NCBIDIR = $(LIBDIR)/ncbi $(BINDIR)/ncbi
-endif
-
-DEFAULT_CRT = $(VDB_SRCDIR)/libs/kfg/certs.kfg
-DEFAULT_KFG = $(VDB_SRCDIR)/libs/kfg/default.kfg
-
-# make reissue command
-MAKE_CMD = $(MAKE) BUILD=$(BUILD) TOOLSET=$(TOOLSET) COMP=$(COMP) LNKG=$(LNKG) \
-    TOP=$(TOP) SRCDIR=$(SRCDIR) OUTDIR=$(OUTDIR) -C $(OBJDIR) -f $(SRCDIR)/Makefile
-
-JMAKE_CMD = $(MAKE) BUILD=$(BUILD) TOOLSET=$(TOOLSET) COMP=$(COMP) LNKG=$(LNKG) \
-    TOP=$(TOP) SRCDIR=$(SRCDIR) OUTDIR=$(OUTDIR) -C $(CLASSDIR) -f $(SRCDIR)/Makefile
-
-# directory and link creation
-SUBDIRS = bin test-bin ilib lib
-OUTDIRS = schema
+TEST_BINDIR = $(TARGDIR)/test-bin
 
 # clean rules
-stdclean:
-	@ -rm -rf $(OBJDIR)
-	@ -rm -rf $(addsuffix .*,$(addprefix $(ILIBDIR)/,$(ALL_LIBS))) \
-			$(addsuffix .*,$(addprefix $(LIBDIR)/,$(ALL_LIBS))) \
-			$(addsuffix -static.*,$(addprefix $(LIBDIR)/,$(ALL_LIBS))) \
-			$(addsuffix *,$(addprefix $(BINDIR)/,$(ALL_TOOLS) $(ALL_LIBS))) \
-			$(addsuffix *,$(addprefix $(TEST_BINDIR)/,$(ALL_TOOLS) $(TEST_TOOLS)))
-
-stdjclean:
-	@ -rm -rf $(CLSPATH) $(CLSDIR)
-
-# removing symbolic links that point to specific builds
-removelinks:
-	@ test ! -h $(OUTDIR)/schema && rm -rf $(OUTDIR)/schema || true
-	@ rm -f $(addprefix $(OUTDIR)/,$(addsuffix $(BITS),$(SUBDIRS)))
-	@ rm -f $(addprefix $(OUTDIR)/,$(OUTDIRS))
-
-$(BINDIR)/ncbi/certs.kfg: $(DEFAULT_CRT)
-	@ mkdir -p $(NCBIDIR)
-	@ cp -v $(DEFAULT_CRT) $@
-
-$(BINDIR)/ncbi/default.kfg: $(DEFAULT_KFG)
-	@ mkdir -p $(NCBIDIR)
-	@ cp -v $(DEFAULT_KFG) $@
-
-# create all required output directories
-makedirs: $(BINDIR)/ncbi/certs.kfg $(BINDIR)/ncbi/default.kfg
-	@ mkdir -p $(addprefix $(TARGDIR)/,$(SUBDIRS) obj/$(MODULE)) $(NCBIDIR)
-
-makejdirs:
-	@ mkdir -p $(CLASSDIR) $(CLSDIR)
-
-# build version include files
-vers-includes: makedirs
-	@ $(MAKE_CMD) -s $(TARGDIR)/$@
-
-ifeq (win,$(OS))
-
-# Windows doesn't really support symbolic links
-# we may add them back in when our toolkit is able to create them
-rebuild-dirlinks: makedirs
-	@ true
-else
-
-LNDIRS = $(addprefix ln_,$(SUBDIRS))
-$(LNDIRS):
-	@ ln -s $(TARGDIR)/$(subst ln_,,$@) $(OUTDIR)/$(subst ln_,,$@)$(BITS)
-
-ifdef NOREBUILD_LINKS
-rebuild-dirlinks:
-	@ true
-else
-rebuild-dirlinks: removelinks makedirs $(LNDIRS)
-	@ ln -s $(VDB_INCDIR) $(OUTDIR)/schema
-endif
-
-endif
-
-.PHONY: stdclean removelinks makedirs vers-includes rebuild-dirlinks
-.PHONY: stdjclean makejdirs
-
-# configuration targets
-out:
-	@ echo $(OUTDIR) > $(TOP)/build/OUTDIR.$(BUILD_OS)
-	@ $(MAKE) TOP=$(TOP) -f $(TOP)/build/Makefile.env rebuild-dirlinks
-
-$(RHOSTS):
-	@ cat $(TOP)/rhosts/$@ >> $(TOP)/build/RHOST.$(HOST_OS)
-
-require-proxy-exec:
-	@ $(MAKE) -C $(TOP)/test/proxy_exec proxy-exec
-	@ echo "PROXY_TOOL := $(BINDIR)/proxy-exec" > $(TOP)/build/RHOST.$(HOST_OS)
-
-local:
-	@ rm -f $(TOP)/build/RHOST.$(HOST_OS)
-
-CC:
-	@ echo cc > $(TOP)/build/COMP.$(OS)
-
-GCC:
-	@ echo gcc > $(TOP)/build/COMP.$(OS)
-
-ICC:
-	@ echo icc > $(TOP)/build/COMP.$(OS)
-
-VC++:
-	@ echo vc++ > $(TOP)/build/COMP.$(OS)
-
-CLANG:
-	@ echo clang > $(TOP)/build/COMP.$(OS)
-
-static dynamic:
-	@ echo "there is no longer any difference between static and dynamic builds"
-
-debug:
-	@ echo dbg > $(TOP)/build/BUILD.$(OS)
-
-profile:
-	@ echo prof > $(TOP)/build/BUILD.$(OS)
-
-release:
-	@ echo rel > $(TOP)/build/BUILD.$(OS)
-
-scm:
-	@ echo scm > $(TOP)/build/BUILD.$(OS)
-
-pubtools: release
-
-bindir:
-	@ echo "$(BINDIR)"
-
-targdir:
-	@ echo "$(TARGDIR)"
-
-osdir:
-	@ echo "$(OUTDIR)/$(OS)"
-
-compilers:
-	@ echo "$(COMPILERS)"
-
-architectures:
-	@ echo "$(ARCHITECTURES)"
-
-architecture:
-	@ echo "$(ARCH)"
+clean:
+	-rm -rf $(OBJDIR) $(ILIBDIR) $(LIBDIR) $(BINDIR) $(TEST_BINDIR)
 
 config:
-	@ echo "  current build is $(LOCAL_OR_REMOTE) $(BUILD_OS) $(BUILD) $(ARCH) build using $(TOOLSET) tools"
-	@ echo "  output target directory is '$(TARGDIR)'"
+	@ echo "Current configuration: $(CONFIGURED)"
+	@ echo "CMake build directory: '$(TARGDIR)/obj'"
+	@ echo "Output target directory: '$(TARGDIR)'"
+	@ echo "Installation target directory: '$(INST_LIBDIR)'"
 	@ echo
 
-purify:
-	@ echo pur > $(TOP)/build/BUILD.$(OS)
+#-------------------------------------------------------------------------------
+# CMake bridge
+#
 
-purecov:
-	@ echo pcov > $(TOP)/build/BUILD.$(OS)
-
-.PHONY: out CC GCC ICC debug profile release scm purify purecov local local require-proxy-exec $(RHOSTS) bindir report_config
-
-# includes based upon build
-ITF   = $(VDB_INCDIR)/
-OSINC = $(VDB_INCDIR)/os
-CCINC = $(VDB_INCDIR)/cc
-XTINC = $(VDB_INCDIR)/ext
-NGSINC = $(NGS_INCDIR)
-OVERRIDEINC = $(TOP)/interfaces/override
-
-# OS specific source and include dirs
-SRCDIRS_OS = $(SRCDIR)/$(OS)
-INCDIRS_OS = $(OSINC)/$(OS)
-
-# most OS' have a parent type
-ifdef OS_DAD
-
-SRCDIRS_OS += $(SRCDIR)/$(OS_DAD)
-INCDIRS_OS += $(OSINC)/$(OS_DAD)
-
-# some OS' have a grandparent
-ifdef OS_GDAD
-SRCDIRS_OS += $(SRCDIR)/$(OS_GDAD)
-INCDIRS_OS += $(OSINC)/$(OS_GDAD)
+ifeq (dbg,$(BUILD))
+    CMAKE_BUILD = Debug
+else
+    CMAKE_BUILD = Release
 endif
 
-endif
+unexport TOP SRCDIR
 
-# compiler specific includes
-INCDIRS_COMP = \
-	$(CCINC)/$(COMP)/$(ARCH) \
-	$(CCINC)/$(COMP)
+# CPP comes from Makefile.config.$(OS_ARCH)
+# TODO: simplify Makefile.config.$(OS_ARCH) generated by ./configure - switch from using LD to a new variable
+CMAKEFLAGS = \
+    -DTARGDIR=$(TARGDIR)                        \
+    -DCMAKE_ARCHIVE_OUTPUT_DIRECTORY=$(ILIBDIR) \
+    -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=$(LIBDIR)  \
+    -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=$(BINDIR)  \
+    -DCMAKE_BUILD_TYPE=$(CMAKE_BUILD)           \
+    -DCMAKE_INSTALL_PREFIX=$(INST_BINDIR)/..    \
+    -DCMAKE_C_COMPILER=$(shell which $(LD))     \
+    -DCMAKE_CXX_COMPILER=$(shell which $(CPP))  \
+    -DVDB_BINDIR=$(VDB_LIBDIR)/.. \
+	-DPYTHON_PATH=$(PYTHON)
 
-# some compilers have a parent type
-ifdef COMP_DAD
+makedirs:
+	mkdir -p $(TARGDIR)/obj
 
-INCDIRS_COMP += \
-	$(CCINC)/$(COMP_DAD)/$(ARCH) \
-	$(CCINC)/$(COMP_DAD)
+cmake_only:
+	cd $(TARGDIR)/obj; cmake $(CMAKEFLAGS) $(TOP)
 
-endif
+cmake: makedirs cmake_only
+	+ make -C $(OBJDIR) --no-print-directory
 
-VPATH = \
-	$(SRCDIR)/$(COMP)/$(ARCH) \
-	$(SRCDIR)/$(COMP) \
-	$(SRCDIRS_OS) \
-	$(SRCDIR)
+ctest: cmake
+	cd $(OBJDIR); ctest $(CMAKEFLAGS) --build-exe-dir $(BINDIR) $(CTESTARGS) -E "^SlowTest_" --verbose
 
-INCDIRS = \
-	$(addprefix -I,$(OVERRIDEINC)) \
-	$(addprefix -I,$(SRCDIRS_OS)) \
-	$(addprefix -I,$(SRCDIR) $(ITF)) \
-	$(addprefix -I,$(INCDIRS_COMP)) \
-	$(addprefix -I,$(INCDIRS_OS)) \
-	$(addprefix -I,$(XTINC) $(NGSINC)) \
-	-I.
+ctestall: cmake
+	cd $(OBJDIR); ctest $(CMAKEFLAGS) --build-exe-dir $(BINDIR) $(CTESTARGS) --verbose
 
+cinstall: cmake
+	+ make -C $(TARGDIR)/obj install
 
-# linker paths
-LDPATHS =
+test runtests: ctest
 
-ifneq (,$(HDF5_LIBDIR))
-	LDPATHS += -L$(HDF5_LIBDIR)
-endif
-ifneq (,$(XML2_LIBDIR))
-	LDPATHS += -L$(XML2_LIBDIR)
-endif
-ifneq (,$(MAGIC_LIBDIR))
-	LDPATHS += -L$(MAGIC_LIBDIR)
-endif
-ifneq (,$(FUSE_LIBDIR))
-	LDPATHS += -L$(FUSE_LIBDIR)
-endif
+slowtests: ctestall
 
-
-# defines that describe os & architecture
-DLLX ?= $(SHLX)
-ARCHDEFS = -D_ARCH_BITS=__SIZEOF_POINTER__*__CHAR_BIT__ -DLIBPREFIX=$(LPFX) -DSHLIBEXT=$(DLLX)
-
-# default tool parameters
-CFLAGS	= -std=c11 $(DEBUG) $(DBG) $(CARCH) $(PROF) $(PED) $(DEFINES) $(ARCHDEFS) $(MIN_DEPLOY_OS_OPT) $(INCDIRS)
-CPFLAGS = -std=c++11 $(DEBUG) $(DBG) $(CARCH) $(PROF) $(DEFINES) $(ARCHDEFS) $(MIN_DEPLOY_OS_OPT) $(INCDIRS)
-LDFLAGS = $(DBG) $(PROF) $(CARCH) $(MIN_DEPLOY_OS_OPT) $(LDPATHS)
+.PHONY: cmake_only cmake ctest ctestall test runtests slowtests
 
 #-------------------------------------------------------------------------------
-# runtests
+# install
 #
-# MallocScribble=1 is for catching allocation problems on Mac
-#
-HOSTNAME = $(shell hostname)
-WHICHASCP = $(shell which ascp 2> /dev/null)
-HAVE_NCBI_ASCP=1
-ifeq (,${WHICHASCP})
-	HAVE_NCBI_ASCP=
-endif
-ifeq (iebdev21,${HOSTNAME})
-	HAVE_NCBI_ASCP=
-endif
+install: cinstall
 
-ifeq ($(RUNTESTS_OVERRIDE),)
-runtests: all $(TEST_TOOLS)
-	@ export VDB_CONFIG=$(VDB_CONFIG);export LD_LIBRARY_PATH=$(LIBDIR):$$LD_LIBRARY_PATH;export MallocScribble=1;\
-	for i in $(TEST_TOOLS);\
-	do\
-		echo ++++++++++++++++++++++++++++++++++++++++++++++++++++++;\
-		echo Run VDB_CONFIG=$$VDB_CONFIG $(TEST_BINDIR)/$$i;eval $(RUN_REMOTELY) $(TEST_BINDIR)/$$i;r=$$?; \
-		if [ "$$r" != "0" ] ; then exit $$r; fi; \
-	done
-
-.PHONY: runtests
-endif
+.PHONY: install
 
 #-------------------------------------------------------------------------------
-# slowtests
+# help
 #
-# $(SLOWTESTSDATADIR) should be used to create temporary test files
-SLOWTESTSDATADIR ?= /panfs/pan1.be-md.ncbi.nlm.nih.gov/sra-test/slowtests/$(shell whoami)
+# TODO:
+help:
+	@ echo
+	@ echo "Before initial build, run './configure --build-prefix=<out>' from"
+	@ echo "the project root to set the output directory of your builds and"
+	@ echo "other parameters."
+	@ echo "Run ./configure -h for full description."
+	@ echo
+	@ echo "Make targets:"
+	@ echo " help            : this text"
+	@ echo " config          : print a summary of current configuration"
+	@ echo " all, std        : full build"
+	@ echo " clean           : remove build results, including CMake-generated files"
+	@ echo " test, runtests  : build and run fast tests"
+	@ echo " slowtests       : build and run all (fast and slow) tests"
+	@ echo " install         : build, install to $(INST_LIBDIR)"
+	@ echo
+	@ echo The build uses CMake. CMake-generated files are in $(OBJDIR)
+	@ echo
+	@ echo It is recommended to use 'make -j' for quicker builds.
+	@ echo
 
-slowtests: all $(SLOW_TEST_TOOLS)
-	@ export LD_LIBRARY_PATH=$(LIBDIR):$$LD_LIBRARY_PATH;\
-	for i in $(SLOW_TEST_TOOLS);\
-	do\
-		echo ++++++++++++++++++++++++++++++++++++++++++++++++++++++;\
-		echo Run $(TEST_BINDIR)/$$i;eval $(RUN_REMOTELY) $(TEST_BINDIR)/$$i;r=$$?; \
-		if [ "$$r" != "0" ] ; then exit $$r; fi; \
-	done
-
-.PHONY: slowtests
+.PHONY: help configure
 
 #-------------------------------------------------------------------------------
-# all-cmn
-#
-# Common target to trigger build of all tools
-#
-$(TARGDIR)/all-cmn: $(addprefix $(BINDIR)/,$(ALL_TOOLS))
 
-.PHONY: $(TARGDIR)/all-cmn
+.PHONY: default all std
 
-#-------------------------------------------------------------------------------
-# std-cmn
-#
-# Common target to trigger build of external visibility tools
-#
-$(TARGDIR)/std-cmn: $(addprefix $(BINDIR)/,$(EXT_TOOLS))
 
-.PHONY: $(TARGDIR)/std-cmn
+# TODO: add support for fuzz testing
+FLIBDIR = $(TARGDIR)/fuzz
+
+$(FLIBDIR):
+	mkdir -p $@
+
+fuzz: makedirs
