VDB-3794 done

diff --git a/build/Makefile.install b/build/Makefile.install
--- a/build/Makefile.install
+++ b/build/Makefile.install
@@ -35,10 +35,11 @@ include $(TOP)/build/Makefile.$(OS)
 # install
 #
 
-# $TOOLS_TO_INSTALL
+# TOOLS_TO_COPY, TOOLS_TO_SYMLINK 
+# $TOOLS_TO_INSTALL = TOOLS_TO_COPY + TOOLS_TO_SYMLINK
 include $(TOP)/build/Makefile.tools
 ifeq (1,$(HAVE_HDF5))
-        TOOLS_TO_INSTALL += pacbio-load
+        TOOLS_TO_COPY += pacbio-load
 endif
 
 # unset outside defined variables
@@ -68,14 +69,27 @@ installexes:
 	@ echo "Installing executables to $(INST_BINDIR)/..."
 	@ mkdir -p $(INST_BINDIR)
 	@ $(MAKE) -s --no-print-directory -f $(TOP)/build/Makefile.install $(TOOLS_TO_INSTALL)
+	@ # copy the driver 
+	@ $(COPY) $(TOP)/tools/driver-tool/sratools.pl $(INST_BINDIR)
+	@ ln -f -s sratools.pl $(INST_BINDIR)/sratools$(EXEX)
+	@ #
 	@ printf "Installing magic file..."
 	@ $(COPY) $(TOP)/tools/copycat/magic $(INST_BINDIR) && echo "done"
 
-$(TOOLS_TO_INSTALL):
+$(TOOLS_TO_COPY):
 	@ printf "Installing $@..."
 	@ # ignore missing tools
 	@ - ( test -f $(BINDIR)/$@$(EXEX) || ( echo "not found" && false ) ) && \
       $(COPY) $(BINDIR)/$@$(EXEX) $(BINDIR)/$@$(VERSION_EXEX) $(BINDIR)/$@$(MAJVERS_EXEX) $(INST_BINDIR) && \
+      echo "done"
+
+$(TOOLS_TO_SYMLINK):
+	@ printf "Installing symlink for $@..."
+	@ # ignore missing tools
+	@ - ( test -f $(BINDIR)/$@$(EXEX) || ( echo "not found" && false ) ) && \
+      $(COPY) $(BINDIR)/$@$(EXEX) $(INST_BINDIR)/$@-orig$(EXEX) && \
+	  ln -f -s sratools $(INST_BINDIR)/$@$(EXEX) && \
+      $(COPY) $(BINDIR)/$@$(VERSION_EXEX) $(BINDIR)/$@$(MAJVERS_EXEX) $(INST_BINDIR) && \
       echo "done"
 
 copykfg:
@@ -108,7 +122,8 @@ endif
 # uninstall
 #
 
-TO_UNINSTALL = $(addsuffix *,$(addprefix $(INST_BINDIR)/,$(TOOLS_TO_INSTALL) magic))
+TO_UNINSTALL = $(addsuffix *,$(addprefix $(INST_BINDIR)/,$(TOOLS_TO_INSTALL) \
+				magic sratools sratools.pl))
 ifneq (true, $(LINUX_ROOT))
     TO_UNINSTALL += $(INST_BINDIR)/ncbi/certs.kfg $(INST_BINDIR)/ncbi/ncbi-vdb.kfg $(INST_BINDIR)/ncbi/default.kfg $(INST_BINDIR)/ncbi/vdb-copy.kfg
 endif
