don't download from asperasoft.com

diff --git a/test/prefetch/Makefile b/test/prefetch/Makefile
--- a/test/prefetch/Makefile
+++ b/test/prefetch/Makefile
@@ -289,15 +289,14 @@ urls_and_accs:
 	@export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; \
 	    $(BINDIR)/prefetch AFVF01 > /dev/null
 	@ls `pwd`/tmp/wgs/AFVF01 > /dev/null
-#	@echo
 
 	@if ls `pwd`/tmp2/100MB 2> /dev/null ; \
      then echo 100MB found ; exit 1; fi
-	@ echo FASP download: asperasoft/100MB
-	@if ascp -h > /dev/null ; \
+	@ echo FASP download: asperasoft/100MB: turned off
+#	@if ascp -h > /dev/null ; \
      then \
 	    export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; cd tmp2 ; \
-	    $(BINDIR)/prefetch $(LARGE) > /dev/null ; \
+	    $(BINDIR)/prefetch $(LARGE) > /dev/null && \
 	    ls `pwd`/100MB > /dev/null ; \
 	 else \
 	    if $(BINDIR)/prefetch $(LARGE) 2> /dev/null ; \
@@ -306,7 +305,17 @@ urls_and_accs:
             exit 1; \
 	     fi ; \
 	 fi
-#	@echo
+
+	@if ascp -h > /dev/null ; \
+     then \
+	    export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; cd tmp2 ; \
+	 else \
+	    if $(BINDIR)/prefetch $(LARGE) 2> /dev/null ; \
+        then \
+            echo "prefetch <FASP URL> when ascp is not found should fail" ; \
+            exit 1; \
+	     fi ; \
+	 fi
 
 	@if ls `pwd`/tmp2/1GB 2> /dev/null; \
      then echo 1GB found ; exit 1; fi
@@ -405,7 +414,7 @@ out_dir_and_file:
 	    echo PREFETCH FASP URL TO OUT-FILE ; \
 	    export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; \
 	    rm -f `pwd`/tmp3/dir/file ; \
-	    $(BINDIR)/prefetch $(LARGE) -O / -o tmp3/dir/file > /dev/null ; \
+	    $(BINDIR)/prefetch $(REFSEQF) -O / -o tmp3/dir/file > /dev/null ; \
 	    ls `pwd`/tmp3/dir/file > /dev/null ; \
 	  else echo download of SRR FASP URL when ascp is not found is disabled ; \
 	  fi
@@ -469,9 +478,9 @@ out_dir_and_file:
 	@ if [ "${HAVE_NCBI_ASCP}" = "1" ] ; then \
 	    echo PREFETCH FASP URL ; \
 	    export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; cd tmp2 ; \
-	    if ls `pwd`/100MB 2> /dev/null ; then exit 1; fi ; \
-	    $(BINDIR)/prefetch $(LARGE) > /dev/null ; \
-	    ls `pwd`/100MB > /dev/null ; \
+	    if ls `pwd`/KC702174.1 2> /dev/null ; then exit 1; fi ; \
+	    $(BINDIR)/prefetch $(REFSEQF) > /dev/null && \
+	    ls `pwd`/KC702174.1 > /dev/null ; \
 	  else echo download of SRR FASP URL when ascp is not found is disabled ; \
 	  fi
 #	@ echo
@@ -522,10 +531,10 @@ out_dir_and_file:
 	@ if [ "${HAVE_NCBI_ASCP}" = "1" ] ; then \
 	    echo PREFETCH FASP URL TO OUT-DIR ; \
 	    export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; \
-	    if ls `pwd`/tmp3/dir/100MB 2> /dev/null ; then \
+	    if ls `pwd`/tmp3/dir/KC702174.1 2> /dev/null ; then \
         echo 100MB found ; exit 1 ; fi ; \
-	    $(BINDIR)/prefetch $(LARGE) -O tmp3/dir > /dev/null ; \
-	    ls `pwd`/tmp3/dir/100MB > /dev/null ; \
+	    $(BINDIR)/prefetch $(REFSEQF) -O tmp3/dir > /dev/null && \
+	    ls `pwd`/tmp3/dir/KC702174.1 > /dev/null ; \
 	  else echo download of SRR FASP URL when ascp is not found is disabled ; \
 	  fi
 #	@ echo
