check that intranet exists before trying to access it

diff --git a/test/prefetch/Makefile b/test/prefetch/Makefile
--- a/test/prefetch/Makefile
+++ b/test/prefetch/Makefile
@@ -60,14 +60,16 @@ urls_and_accs:
 	    fi
 
 	@export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; \
-	    if $(BINDIR)/prefetch http://intranet/ 2>/dev/null ; \
-        then echo "prefetch URL-2 when there is no kfg should fail"; exit 1; \
-	    fi
+	    ping -c1 intranet > /dev/null && \
+	     ( if $(BINDIR)/prefetch http://intranet/ 2>/dev/null ; \
+	       then echo "prefetch URL-2 when there is no kfg should fail"; exit 1; \
+	       fi )
 
 	@export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; \
-	    if $(BINDIR)/prefetch http://intranet/irb/support.shtml  2>/dev/null ; \
-	    then echo "prefetch URL-2 when there is no kfg should fail"; exit 1; \
-	    fi
+	    ping -c1 intranet > /dev/null && \
+	    (if $(BINDIR)/prefetch http://intranet/irb/support.shtml  2>/dev/null ; \
+	     then echo "prefetch URL-2 when there is no kfg should fail"; exit 1; \
+	     fi )
 
 	@echo '$(PUBLIC)/apps/file/volumes/flat = "files"' > tmp/t.kfg
 	@echo '$(PUBLIC)/root = "$(CWD)/tmp"' >> tmp/t.kfg
@@ -76,28 +78,32 @@ urls_and_accs:
      then echo support.shtml found ; exit 1 ; fi
 	@echo HTTP download when user repository is configured
 	@export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; cd tmp2 ; \
-	    $(BINDIR)/prefetch http://intranet/irb/support.shtml > /dev/null
-	@ls `pwd`/tmp2/support.shtml > /dev/null
+	    ping -c1 intranet > /dev/null && \
+	    $(BINDIR)/prefetch http://intranet/irb/support.shtml > /dev/null 
+	@ping -c1 intranet > /dev/null && ls `pwd`/tmp2/support.shtml > /dev/null
 #	@echo
 
 	@echo Running prefetch second time finds previous download
 	@export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; cd tmp2 ; \
-	    $(BINDIR)/prefetch http://intranet/irb/support.shtml \
-            | grep "found local" > /dev/null
+	 ping -c1 intranet > /dev/null && \
+	 $(BINDIR)/prefetch http://intranet/irb/support.shtml \
+	        | grep "found local" > /dev/null
 #	@echo
 
 	@if ls `pwd`/tmp2/index.html 2> /dev/null ; \
      then echo index.shtml found ; exit 1; fi
 	@echo HTTP download when user repository is configured
 	@export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; cd tmp2 ; \
+	 ping -c1 intranet > /dev/null && \
 	    $(BINDIR)/prefetch http://intranet/ > /dev/null
-	@ls `pwd`/tmp2/index.html > /dev/null
+	@ping -c1 intranet > /dev/null && ls `pwd`/tmp2/index.html > /dev/null
 #	@echo
 
 	@echo Running prefetch second time finds previous download
 	@export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; cd tmp2 ; \
+	 ping -c1 intranet > /dev/null && \
 	    $(BINDIR)/prefetch http://intranet/ | grep "found local" > /dev/null
-	@rm tmp2/index.html
+	@rm -f tmp2/index.html
 #	@echo
 
 	@echo URL download when user repository is configured
