VDB-3533: added tests for download of URS-s of all accession types

diff --git a/test/prefetch/Makefile b/test/prefetch/Makefile
--- a/test/prefetch/Makefile
+++ b/test/prefetch/Makefile
@@ -1,12 +1,13 @@
 default: runtests
-
 TOP ?= $(abspath ../..)
-
 include $(TOP)/build/Makefile.env
-
 CWD = $(shell pwd)
 PUBLIC=/repository/user/main/public
-RUN=https://sra-download.ncbi.nlm.nih.gov/traces/sra6/SRR/000052/SRR053325
+SRA=https://sra-download.ncbi.nlm.nih.gov
+KMER=$(SRA)/traces/nannot01/kmer/000/390/GCA_000390265.1_R
+REFSEQ=$(SRA)/traces/refseq/KC702174.1
+SRR=$(SRA)/traces/sra6/SRR/000052/SRR053325
+WGS=$(SRA)/traces/wgs03/WGS/AF/VF/AFVF01.1
 
 runtests: check_prefetch
 
@@ -30,21 +31,64 @@ check_prefetch:
 	export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; cd tmp2 ; \
 	    $(BINDIR)/prefetch https://github.com/ncbi/ngs/wiki | grep "found local"
 
-
 	export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; \
-	    if $(BINDIR)/prefetch $(RUN); then exit 1; \
+	    if $(BINDIR)/prefetch $(SRR); then exit 1; \
 	    else echo "^^^ failure when user repository is not set is expected"; \
 	    echo; fi
 
 	echo '$(PUBLIC)/root = "$(CWD)/tmp"' >> tmp/t.kfg
 	@echo SRR download when user repository is configured
 	export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; \
-	    $(BINDIR)/prefetch $(RUN)
+	    $(BINDIR)/prefetch $(SRR)
 	@echo
 
 	@echo Running prefetch second time finds previous download
 	export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; \
-	    $(BINDIR)/prefetch $(RUN) | grep "found local"
+	    $(BINDIR)/prefetch $(SRR) | grep "found local"
+	@echo
+
+	export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; \
+	    if $(BINDIR)/prefetch $(REFSEQ); then exit 1; \
+	    else echo "^^^ failure when user repository is incomplete is expected"; \
+	    echo; fi
+
+	echo '$(PUBLIC)/apps/refseq/volumes/refseq = "refseq"' >> tmp/t.kfg
+	@echo REFSEQ download when user repository is configured
+	export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; \
+	    $(BINDIR)/prefetch $(REFSEQ)
+	@echo
+
+	@echo Running prefetch second time finds previous download
+	export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; \
+	    $(BINDIR)/prefetch $(REFSEQ) | grep "found local"
+	@echo
+
+	export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; \
+	    if $(BINDIR)/prefetch $(KMER); then exit 1; \
+	    else echo "^^^ failure when user repository is incomplete is expected"; \
+	    echo; fi
+
+	echo '$(PUBLIC)/apps/nakmer/volumes/nakmerFlat = "nannot"' >> tmp/t.kfg
+	@echo NANNOT download when user repository is configured
+	export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; \
+	    $(BINDIR)/prefetch $(KMER)
+	@echo
+
+	@echo Running prefetch second time finds previous download
+	export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; \
+	    $(BINDIR)/prefetch $(KMER) | grep "found local"
+	@echo
+
+	export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; \
+	    if $(BINDIR)/prefetch $(WGS); then exit 1; \
+	    else echo "^^^ failure when user repository is incomplete is expected"; \
+	    echo; fi
+
+	echo '$(PUBLIC)/apps/wgs/volumes/wgsFlat = "wgs"' >> tmp/t.kfg
+	@echo WGS download when user repository is configured
+	export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; \
+	    $(BINDIR)/prefetch $(WGS)
+	@echo
 
 #	export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; $(BINDIR)/vdb-config -on
 
