VDB-3533: tests for HTTP URL-s downloads

diff --git a/test/prefetch/Makefile b/test/prefetch/Makefile
--- a/test/prefetch/Makefile
+++ b/test/prefetch/Makefile
@@ -26,30 +26,62 @@ check_prefetch:
 	    else echo "^^^ failure when user repository is not set is expected"; \
 	    echo; fi
 
+	export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; \
+	    if $(BINDIR)/prefetch http://intranet/; then exit 1; \
+	    else echo "^^^ failure when user repository is not set is expected"; \
+	    echo; fi
+
+	export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; \
+	    if $(BINDIR)/prefetch http://intranet/irb/support.shtml; then exit 1; \
+	    else echo "^^^ failure when user repository is not set is expected"; \
+	    echo; fi
+
 	echo '$(PUBLIC)/apps/sra/volumes/sraFlat = "sra"' > tmp/t.kfg
+
+	@echo HTTP download when user repository is configured
+	@export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; cd tmp2 ; \
+	    $(BINDIR)/prefetch http://intranet/irb/support.shtml
+	@echo
+
+	@echo Running prefetch second time finds previous download
+	@export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; cd tmp2 ; \
+	    $(BINDIR)/prefetch http://intranet/irb/support.shtml | grep "found local"
+	@echo
+
+	@echo HTTP download when user repository is configured
+	@export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; cd tmp2 ; \
+	    $(BINDIR)/prefetch http://intranet/ > /dev/null
+	@echo
+
+	@echo Running prefetch second time finds previous download
+	@export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; cd tmp2 ; \
+	    $(BINDIR)/prefetch http://intranet/ | grep "found local"
+	@rm -v tmp2/index.html
+	@echo
 
 	@echo URL download when user repository is configured
 	@export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; cd tmp2 ; \
 	    $(BINDIR)/prefetch https://github.com/ncbi/ngs/wiki > /dev/null
 	@echo
 
-	@#echo URL/ download when user repository is configured
-	export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; cd tmp2 ; \
-	    $(BINDIR)/prefetch https://github.com/ncbi/
+	@echo Running prefetch second time finds previous download
+	@export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; cd tmp2 ; \
+	    $(BINDIR)/prefetch https://github.com/ncbi/ngs/wiki \
+	                              | grep "found local" > /dev/null
 	@echo
 
-	@echo Running prefetch second time finds previous download
-	export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; cd tmp2 ; \
-	    $(BINDIR)/prefetch https://github.com/ncbi/ | grep "found local"
+	@echo URL/ download when user repository is configured
+	@export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; cd tmp2 ; \
+	    $(BINDIR)/prefetch https://github.com/ncbi/ > /dev/null
 	@echo
 
 	@echo Running prefetch second time finds previous download
 	@export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; cd tmp2 ; \
-	    $(BINDIR)/prefetch https://github.com/ncbi/ngs/wiki | grep "found local"
+	    $(BINDIR)/prefetch https://github.com/ncbi/ |grep "found local">/dev/null
 
 	@export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; \
-	    if $(BINDIR)/prefetch $(SRR); then exit 1; \
-	    else echo "^^^ failure when user repository is not set is expected"; \
+	    if $(BINDIR)/prefetch $(SRR) 2> /dev/null ; then exit 1; \
+	    else echo "Failure when user repository is not set is expected"; \
 	    echo; fi
 
 	echo '$(PUBLIC)/root = "$(CWD)/tmp"' >> tmp/t.kfg
@@ -60,11 +92,11 @@ check_prefetch:
 
 	@echo Running prefetch second time finds previous download
 	@export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; \
-	    $(BINDIR)/prefetch $(SRR) | grep "found local"
+	    $(BINDIR)/prefetch $(SRR) | grep "found local" > /dev/null
 
 	@export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; \
-	    if $(BINDIR)/prefetch $(REFSEQ); then exit 1; \
-	    else echo "^^^ failure when user repository is incomplete is expected"; \
+	    if $(BINDIR)/prefetch $(REFSEQ) 2> /dev/null ; then exit 1; \
+	    else echo "Failure when user repository is incomplete is expected"; \
 	    echo; fi
 
 	echo '$(PUBLIC)/apps/refseq/volumes/refseq = "refseq"' >> tmp/t.kfg
@@ -75,7 +107,7 @@ check_prefetch:
 
 	@echo Running prefetch second time finds previous download
 	@export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; \
-	    $(BINDIR)/prefetch $(REFSEQ) | grep "found local"
+	    $(BINDIR)/prefetch $(REFSEQ) | grep "found local" > /dev/null
 
 	@export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; \
 	    if $(BINDIR)/prefetch $(KMER) 2> /dev/null ; then exit 1; \
@@ -90,7 +122,7 @@ check_prefetch:
 
 	@echo Running prefetch second time finds previous download
 	@export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; \
-	    $(BINDIR)/prefetch $(KMER) | grep "found local"
+	    $(BINDIR)/prefetch $(KMER) | grep "found local" > /dev/null
 
 	@export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; \
 	    if $(BINDIR)/prefetch $(WGS) 2> /dev/null; then exit 1; \
