VDB-3533: download non-accession objects to the current directory when URL is requested

diff --git a/test/prefetch/Makefile b/test/prefetch/Makefile
--- a/test/prefetch/Makefile
+++ b/test/prefetch/Makefile
@@ -12,9 +12,24 @@ runtests: check_prefetch
 
 ################################################################################
 check_prefetch:
-	@mkdir -pv tmp
-	@echo
+	@mkdir -pv tmp tmp2
+	echo 'foo = "bar"' > tmp/t.kfg
+
+	export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; \
+	    if $(BINDIR)/prefetch https://github.com/ncbi/ngs/wiki; then exit 1; \
+	    else echo "^^^ failure when user repository is not set is expected"; \
+	    echo; fi
+
 	echo '$(PUBLIC)/apps/sra/volumes/sraFlat = "sra"' > tmp/t.kfg
+
+	export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; cd tmp2 ; \
+	    $(BINDIR)/prefetch https://github.com/ncbi/ngs/wiki
+	@echo
+
+	@echo Running prefetch second time finds previous download
+	export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; cd tmp2 ; \
+	    $(BINDIR)/prefetch https://github.com/ncbi/ngs/wiki | grep "found local"
+
 
 	export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; \
 	    if $(BINDIR)/prefetch $(RUN); then exit 1; \
@@ -27,11 +42,11 @@ check_prefetch:
 	    $(BINDIR)/prefetch $(RUN)
 	@echo
 
-	@echo URL download when user repository is configured
+	@echo Running prefetch second time finds previous download
 	export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; \
-	    $(BINDIR)/prefetch https://github.com/ncbi/ngs/wiki
+	    $(BINDIR)/prefetch $(RUN) | grep "found local"
 
 #	export VDB_CONFIG=`pwd`/tmp; export NCBI_SETTINGS=/ ; $(BINDIR)/vdb-config -on
 
 	@echo
-	@rm -rv tmp
+	@rm -rv tmp*
