1343: Moved all configuration scripts to setup/; Added install scripts

diff --git a/setup/install b/setup/install
--- a/setup/install
+++ b/setup/install
@@ -29,17 +29,17 @@ CURDIR="`dirname $0`"
 
 if [ -z "$CURDIR" ]
     then
-    echo configure: error: configure should be run as ./configure
+    echo error: install should be run as ./install
     exit 1
 fi
 
-if [ "$FILENAME" != configure -a ! -s setup/konfigure.perl ]
+if [ "$FILENAME" != install -a ! -s install.perl ]
     then
-    echo configure: error: configure should be run as ./configure
+    echo error: install should be run as ./install
 else
     perl -v > /dev/null 2>&1 || { echo "checking for perl... no"; \
-        echo >&2 "configure: error: perl not found."; exit 1; }
+        echo >&2 "error: perl not found."; exit 1; }
 
-    cd $CURDIR/setup
-    perl -w konfigure.perl "$@"
+    cd $CURDIR
+    perl -w ./install.perl "$@"
 fi
